backend:
  name: github
  repo: vih/fond-jekyll
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "exerpt", widget: "text"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Category", name: "category", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Header
        name: header
        widget: object
        collapsed: true
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "image", required: false}
          - {label: "Teaser Image", name: "teaser", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "text"}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime"}
      - {label: "TOC", name: "toc", widget: "boolean", default: true}
      - label: Feature row
        name: feature_row
        widget: list
        collapsed: true
        fields:
          - {label: "Overlay Image", name: "image_path", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Alt", name: "alt", widget: "string"}
          - {label: "Exerpt", name: "exerpt", widget: "text"}
          - {label: "Url", name: "url", widget: "string"}
          - {label: "Btn label", name: "btn_label", widget: "string"}
          - {label: "Btn class", name: "btn_class", widget: "select", options: ["btn--success", "btn--warning", "btn--danger"], default: "btn--success"}
